[package]
name = "audio_effects"
version = "0.1.0"
authors = ["Richard A. Healy <rahealy@users.noreply.github.com>"]
edition = "2018"

[dependencies.rack]
path = "rack"

[dependencies.shared]
path = "shared"

[dependencies.effects]
path = "effects"
